import Head from 'next/head'
import Image from 'next/image'
import Script from 'next/script'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome to the Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="keywords" content="next ,hunting coder, huntingcoder blog" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Script src="/sc.js" strategy="lazyOnload"></Script>
       */}
      <nav className={styles.mainnav}>
        <ul>
          <Link href='/'><li>Home</li></Link>
          <Link href='/about'><li>About</li></Link>
          <Link href='/blog'><li>Blog</li></Link>
          <Link href='/contact'><li>Contact</li></Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>Hunting Coder</h1>

        <p className={styles.description}>
          A hunting coder by hunting coder
        </p>

        <h2>Popular Blogs</h2>
        <div className="blogs">
          <div className="blogItem">
            <h3>How to learn Javascript in 2023?</h3>
            <p>Javascript is the language used to design logic for web.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2023?</h3>
            <p>Javascript is the language used to design logic for web.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2023?</h3>
            <p>Javascript is the language used to design logic for web.</p>
          </div>
          <div className="blogItem">
            <h3>How to learn Javascript in 2023?</h3>
            <p>Javascript is the language used to design logic for web.</p>
          </div>
        </div>
      </main>
    </>
  )
}
